-- MySQL Script generated by MySQL Workbench
-- Wed Jun 10 19:59:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema honduTours_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema honduTours_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `honduTours_db` DEFAULT CHARACTER SET utf8 ;
USE `honduTours_db` ;

-- -----------------------------------------------------
-- Table `honduTours_db`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honduTours_db`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;

-----------------------------------------------------
-- Table `honduTours_db`.`Info_Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honduTours_db`.`Info_Lugar` (
  `idInfo_Lugar` INT NOT NULL AUTO_INCREMENT,
  `nombre_Lugar` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL,
  `latitud` DECIMAL(10,8) NULL,
  `longitud` DECIMAL(10,8) NULL,
  `direccion_Lugar` VARCHAR(255) NULL,
  `departamento_HN` VARCHAR(100) NULL,
  `imagen_Lugar` VARCHAR(255) NULL,
  `precio` DECIMAL(10,2) NULL,
  `personas_disponibilidad` INT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idInfo_Lugar`),
  INDEX `fk_Info_Lugar_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Info_Lugar_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `honduTours_db`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `honduTours_db`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honduTours_db`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_Usuario` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(200) NULL,
  `correo` VARCHAR(45) NULL,
  `registro_Fech` DATETIME NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;

ALTER TABLE Usuarios
ADD COLUMN rol ENUM('ADMIN', 'CLIENTE') NOT NULL DEFAULT 'CLIENTE';

select * from Usuarios;

INSERT INTO Usuarios (
  nombre_Usuario,
  contrasenia,
  correo,
  registro_Fech,
  rol
)
VALUES (
  'Alexander M',
  '123456',
  'alex@demo.com',
  NOW(),
  'ADMIN'
);

INSERT INTO Usuarios (
  nombre_Usuario,
  contrasenia,
  correo,
  registro_Fech,
  rol
)
VALUES (
  'Marlon M',
  '4321',
  'marlon@gamil.com',
  NOW(),
  'CLIENTE'
);
-- -----------------------------------------------------
-- Table `honduTours_db`.`Favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honduTours_db`.`Favoritos` (
  `idFavoritos` INT NOT NULL AUTO_INCREMENT,
  `Info_Lugar_idInfo_Lugar` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idFavoritos`),
  INDEX `fk_Favoritos_Info_Lugar_idx` (`Info_Lugar_idInfo_Lugar` ASC) VISIBLE,
  INDEX `fk_Favoritos_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Favoritos_Info_Lugar`
    FOREIGN KEY (`Info_Lugar_idInfo_Lugar`)
    REFERENCES `honduTours_db`.`Info_Lugar` (`idInfo_Lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favoritos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `honduTours_db`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `honduTours_db`.`Creacion_Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honduTours_db`.`Creacion_Plan` (
  `idCreacion_Plan` INT NOT NULL AUTO_INCREMENT,
  `nombre_plan` VARCHAR(100) NULL,
  `fecha_plan` DATETIME NULL,
  `dias_plan` INT NULL,
  `capacidad_personas` INT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idCreacion_Plan`),
  INDEX `fk_Creacion_Plan_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Creacion_Plan_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `honduTours_db`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from Creacion_plan;
-- -----------------------------------------------------
-- Table `honduTours_db`.`Plan_Detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honduTours_db`.`Plan_Detalles` (
  `idPlan_Detalles` INT NOT NULL AUTO_INCREMENT,
  `Creacion_Plan_idCreacion_Plan` INT NOT NULL,
  `Info_Lugar_idInfo_Lugar` INT NOT NULL,
  `fecha_visita` DATETIME NULL,
  PRIMARY KEY (`idPlan_Detalles`),
  INDEX `fk_Plan_Detalles_Creacion_Plan1_idx` (`Creacion_Plan_idCreacion_Plan` ASC) VISIBLE,
  INDEX `fk_Plan_Detalles_Info_Lugar1_idx` (`Info_Lugar_idInfo_Lugar` ASC) VISIBLE,
  CONSTRAINT `fk_Plan_Detalles_Creacion_Plan1`
    FOREIGN KEY (`Creacion_Plan_idCreacion_Plan`)
    REFERENCES `honduTours_db`.`Creacion_Plan` (`idCreacion_Plan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plan_Detalles_Info_Lugar1`
    FOREIGN KEY (`Info_Lugar_idInfo_Lugar`)
    REFERENCES `honduTours_db`.`Info_Lugar` (`idInfo_Lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO Categoria (nombre_categoria) VALUES
('Playas y Costas'),
('Islas del Caribe'),
('Parques Nacionales'),
('Montañas y Bosques'),
('Cascadas'),
('Ruinas Mayas'),
('Pueblos con Encanto'),
('Turismo de Aventura'),
('Ecoturismo'),
('Turismo Cultural');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Info_Lugar (
  nombre_Lugar,
  descripcion,
  latitud,
  longitud,
  direccion_Lugar,
  departamento_HN,
  imagen_Lugar,
  precio,
  personas_disponibilidad,
  Categoria_idCategoria
)
VALUES (
  'Roatán',
  'Isla paradisíaca del Caribe hondureño, famosa por sus playas y arrecifes.',
  16.3163,
  -86.5370,
  'Isla de Roatán',
  'Islas de la Bahía',
  'roatán.jpg',
  150.00,
  50,
  1
);

INSERT INTO Info_Lugar (
  nombre_Lugar,
  descripcion,
  latitud,
  longitud,
  direccion_Lugar,
  departamento_HN,
  imagen_Lugar,
  precio,
  personas_disponibilidad,
  Categoria_idCategoria
)
VALUES (
  'Cataratas de Pulhapanzak',
  'Una de las cascadas más grandes y turísticas de Honduras.',
  14.9175,
  -87.9758,
  'San Buenaventura',
  'Cortés',
  'pulhapanzak.jpg',
  80.00,
  100,
  4
);

INSERT INTO Info_Lugar (
  nombre_Lugar,
  descripcion,
  latitud,
  longitud,
  direccion_Lugar,
  departamento_HN,
  imagen_Lugar,
  precio,
  personas_disponibilidad,
  Categoria_idCategoria
)
VALUES (
  'Ruinas de Copán',
  'Ciudad maya arqueológica reconocida mundialmente por su historia.',
  14.8410,
  -89.1565,
  'Copán Ruinas',
  'Copán',
  'copan.jpg',
  120.00,
  80,
  7
);

INSERT INTO Info_Lugar (
  nombre_Lugar,
  descripcion,
  latitud,
  longitud,
  direccion_Lugar,
  departamento_HN,
  imagen_Lugar,
  precio,
  personas_disponibilidad,
  Categoria_idCategoria
)
VALUES (
  'Lago de Yojoa',
  'El lago más grande de Honduras, rodeado de naturaleza y biodiversidad.',
  14.8857,
  -87.9640,
  'Entre Cortés, Comayagua y Santa Bárbara',
  'Zona Centro-Norte',
  'yojoa.jpg',
  60.00,
  200,
  8
);

select * from Info_Lugar;
	

INSERT INTO Info_Lugar (nombre_Lugar, descripcion, latitud, longitud, direccion_Lugar, departamento_HN, imagen_Lugar, precio, personas_disponibilidad, Categoria_idCategoria) VALUES 
('Bahía de Tela', 'Hermosas playas de arena blanca, aguas cristalinas y comunidades garífunas llenas de cultura.', 15.7752, -87.4526, 'Costas de Tela', 'Atlántida', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e', 50.00, 150, 1),
('Isla de Utila', 'Famosa mundialmente por ser uno de los lugares más económicos y hermosos para certificar el buceo.', 16.0994, -86.9317, 'Islas de la Bahía', 'Islas de la Bahía', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa', 110.00, 60, 2),
('Parque Nacional Pico Bonito', 'Imponente parque nacional con una biodiversidad increíble y el famoso río Cangrejal.', 15.6792, -86.8622, 'La Ceiba', 'Atlántida', 'https://images.unsplash.com/photo-1448375240586-882707db888b', 40.00, 100, 3),
('Parque Nacional Celaque', 'Hogar del punto más alto de Honduras, rodeado de un misterioso y denso bosque nublado.', 14.5442, -88.6536, 'Gracias', 'Lempira', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b', 35.00, 80, 4),
('Cascada Río Zacate', 'Hermosa caída de agua cristalina que desciende directamente de las alturas de Pico Bonito.', 15.7115, -86.9181, 'Parque Nacional Pico Bonito', 'Atlántida', 'https://images.unsplash.com/photo-1432406186267-e81979265944', 30.00, 50, 5),
('Parque Arqueológico El Puente', 'Importante ciudad satélite de la civilización maya con estructuras y montículos restaurados.', 15.1118, -88.8021, 'La Jigua', 'Copán', 'https://upload.wikimedia.org/wikipedia/commons/e/ec/El_Puente_Structure_1.jpg', 70.00, 120, 6),
('Valle de Ángeles', 'Pueblo colonial famoso por su clima fresco, deliciosa gastronomía y artesanías hechas a mano.', 14.1528, -87.0372, 'Casco Urbano', 'Francisco Morazán', 'https://images.unsplash.com/photo-1534430480872-3498386e7a69', 20.00, 300, 7),
('Cuevas de Taulabé', 'Impresionante sistema de cuevas subterráneas con formaciones naturales de estalactitas y estalagmitas.', 14.6953, -87.9708, 'Taulabé', 'Comayagua', 'https://images.unsplash.com/photo-1507163879411-569c6115702c', 45.00, 150, 8),
('Jardín Botánico Lancetilla', 'El segundo jardín botánico tropical más grande del mundo, ideal para el avistamiento de aves.', 15.7366, -87.4542, 'Lancetilla', 'Atlántida', 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5', 50.00, 250, 9),
('Centro Histórico de Comayagua', 'Antigua capital colonial nacional que alberga la catedral con el reloj más viejo de América en funcionamiento.', 14.4513, -87.6374, 'Plaza Central León Alvarado', 'Comayagua', 'https://images.unsplash.com/photo-1564507592333-c60657eea523', 25.00, 400, 10);

-- -----------------------------------------------------
-- Se deja informacion para uso de la base de datos
-- -----------------------------------------------------